---
title: ""
---

### PANTHER intervention selection committee membership

<br />

**Chair**

Dr Jonathan Millar (University of Edinburgh, United Kingdom)

<br />

**Members**

A/Prof Lieuwe Bos (University of Amsterdam, Netherlands)

Prof Carolyn Calfee (University of California San Francisco, United States)

A/Prof Clark Files (Wake Forest University, United States)

Prof Susanne Herold (University of Giessen, Germany)

Prof Anthony Gordon (Imperial College London, United Kingdom)

A/Prof Patrick Lawler (University of Toronto, Canada)

Prof John Marshall (University of Toronto, Canada)

Prof Tom Martin (University of Washington, United States)

A/Prof David Maslove (Queen's University, Canada)

Prof Alistair Nichol (University College Dublin, Ireland)

Prof Cecilia O'Kane (Queen's University Belfast, United Kingdom)

Prof Andrew Owen (University of Liverpool, United Kingdom)

Dr Tony Rostron (Newcastle University, United Kingdom)

Prof Manu Shankar-Hari (University of Edinburgh, United Kingdom)