---
title: ""
---

### Assessment criteria

Candidate interventions are discussed and assessed by the platform intervention selection committee based on the criteria set out below.

<br />

#### **Domain 1 - Evidence base**

::: {.callout-note icon=false collapse=true}
## 1.1 \ \ \ \ Sub-phenotype

-    **Is there evidence of a differential response to the proposed intervention among sub-phenotypes of ARDS?**

Levels:

-    Pre-clinical
-    Observational
-    Re-analysis of a randomised controlled trial

Grades: *Strong, moderate, or weak*

-    **Are these sub-phenotypes consistent with the PANTHER platforms approach to stratification?**

-    **Is there sufficient evidence to suggest the mechanism by which the intervention exerts benefit and is further investigation of this mechanism tractable within the platform?**
:::

::: {.callout-note icon=false collapse=true}
## 1.2 \ \ \ \ ARDS

-    **Is there evidence of efficacy in ARDS?**

Levels:

-    Pre-clinical
-    Observational
-    Randomised controlled trial

Grades: *Strong, moderate, or weak*
:::

::: {.callout-note icon=false collapse=true}
## 1.3 \ \ \ \ COVID-19 ARDS

-    **Is there evidence of efficacy in COVID-19 ARDS?**

Levels:

-    Pre-clinical
-    Observational
-    Randomised controlled trial

Grades: *Strong, moderate, or weak*
:::

::: {.callout-note icon=false collapse=true}
## 1.4 \ \ \ \ Related condition

-    **Is there evidence of efficacy in an inflammatory condition related to ARDS?**

Levels:

-    Pre-clinical
-    Observational
-    Randomised controlled trial

Grades: *Strong, moderate, or weak*

-    **Does sufficient mechanistic data exist to show that similar effects could reasonably be expected in an ARDS sub-phenotype?**
:::

<br />

#### **Domain 2 - Safety and pharmacology data**

::: {.callout-note icon=false collapse=true}
## 2.1 \ \ \ \ Safety

-    **At what phase of development is the intervention?**

-    **Does the intervention have important cautions or contraindications?**

-    **Does the intervention have important interactions?**

-    **What are the common or important side-effects?**

-    **Is a reversal agent available?**
:::

::: {.callout-note icon=false collapse=true}
## 2.2 \ \ \ \ PK/PD data

-    **Is robust PK/PD data available?**

-    **If so, are data specific to a critical illness population? Do these data extend to patients in receipt of RRT and/or ECMO?**
:::

<br />

#### **Domain 3 - Feasibility**

::: {.callout-note icon=false collapse=true}
## 3.1 \ \ \ \ Suitable formulation

-    **Is there a formulation of the intervention that is suitable for administration to critically ill and mechanically ventilated patients?**

-    **Does the proposed intervention require special preparation, storage or handling?**

-    **What is the anticipated duration of the intervention and what is the dosing schedule?**
:::

::: {.callout-note icon=false collapse=true}
## 3.2 \ \ \ \ Scalable to trial

-    **Is the supply of the intervention scalable to an international, multi-centre study?**

-    **Can the supply of the intervention be guaranteed for the anticipated duration of recruitment?**

-    **For repurposed interventions, what is the prevalence of use in the population that the trial seeks to include?**

-    **Does the intervention require therapeutic drug monitoring?**

-    **Does the intervention require the use of an additional biomarker to guide administration?**
:::

::: {.callout-note icon=false collapse=true}
## 3.3 \ \ \ \ Ongoing or planned studies

-    **Are there ongoing or planned studies of the intervention in the same or a similar population? If so, would inclusion of the intervention in PANTHER be likely to offer novel or superior information?**
:::








